ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "auth_id" uuid;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_auth_id_users_id_fk" FOREIGN KEY ("auth_id") REFERENCES "auth"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_auth_id_unique" UNIQUE("auth_id");--> statement-breakpoint
CREATE POLICY "attachments_owner_select" ON "attachments" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("attachments"."owner_id" = (select id from public.users where auth_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "attachments_owner_insert" ON "attachments" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("attachments"."owner_id" = (select id from public.users where auth_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "attachments_owner_update" ON "attachments" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("attachments"."owner_id" = (select id from public.users where auth_id = (select auth.uid()))) WITH CHECK ("attachments"."owner_id" = (select id from public.users where auth_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "attachments_owner_delete" ON "attachments" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("attachments"."owner_id" = (select id from public.users where auth_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "notes_owner_select" ON "notes" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("notes"."owner_id" = (select id from public.users where auth_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "notes_owner_insert" ON "notes" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("notes"."owner_id" = (select id from public.users where auth_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "notes_owner_update" ON "notes" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("notes"."owner_id" = (select id from public.users where auth_id = (select auth.uid()))) WITH CHECK ("notes"."owner_id" = (select id from public.users where auth_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "notes_owner_delete" ON "notes" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("notes"."owner_id" = (select id from public.users where auth_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "projects_owner_select" ON "projects" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("projects"."owner_id" = (select id from public.users where auth_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "projects_owner_insert" ON "projects" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("projects"."owner_id" = (select id from public.users where auth_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "projects_owner_update" ON "projects" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("projects"."owner_id" = (select id from public.users where auth_id = (select auth.uid()))) WITH CHECK ("projects"."owner_id" = (select id from public.users where auth_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "projects_owner_delete" ON "projects" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("projects"."owner_id" = (select id from public.users where auth_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "reminders_owner_select" ON "reminders" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("reminders"."owner_id" = (select id from public.users where auth_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "reminders_owner_insert" ON "reminders" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("reminders"."owner_id" = (select id from public.users where auth_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "reminders_owner_update" ON "reminders" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("reminders"."owner_id" = (select id from public.users where auth_id = (select auth.uid()))) WITH CHECK ("reminders"."owner_id" = (select id from public.users where auth_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "reminders_owner_delete" ON "reminders" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("reminders"."owner_id" = (select id from public.users where auth_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "tasks_owner_select" ON "tasks" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("tasks"."owner_id" = (select id from public.users where auth_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "tasks_owner_insert" ON "tasks" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ("tasks"."owner_id" = (select id from public.users where auth_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "tasks_owner_update" ON "tasks" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("tasks"."owner_id" = (select id from public.users where auth_id = (select auth.uid()))) WITH CHECK ("tasks"."owner_id" = (select id from public.users where auth_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "tasks_owner_delete" ON "tasks" AS PERMISSIVE FOR DELETE TO "authenticated" USING ("tasks"."owner_id" = (select id from public.users where auth_id = (select auth.uid())));--> statement-breakpoint
CREATE POLICY "users_read_own" ON "users" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("users"."auth_id" = (select auth.uid()));